#!/usr/bin/env php
<?php
/**
 * ## Server Controller. Commands:
 * # Load nginx/php-fpm/mysql
 * serv [(start|stop|reload... - any parameters that nginx/php-fpm/mysql accept)]
 * # Load nginx/php-fpm
 * serv-min [(start|stop|reload... - any parameters that nginx/php-fpm accept)]
 */

require('src/root');
/**
 * ANSI escape code
 * @var string
 */
$CSI = "\x1B[";

/**
 * HELP
 */
new Help($argv);
if (!isset($argv[1])) {
	new Help($argv += [1 => '-h']);
}

/**
 * Configuration
 */

echo "\n".$CSI."36;40m" . "--- CLIKE CLI received following parameters:" . $CSI . "0m". "\n";

for ($i=1; $i < count($argv); $i++)
{
	echo '['.$argv[$i].'] ';
}
echo "\n\n";

switch (strstr($argv[1], ':', true)?: $argv[1]) {
	case 'config':
		new Help($argv);
		break;
	case 'server':
		new Server($argv)?: new Help($argv);
		break;
	case 'git':
		new Git($argv)?: new Help($argv);
		break;
	case 'storage':
		new Help($argv);
		break;

	default:
		new Help($argv);
		break;
}
