#!/usr/bin/env php
<?php
/**
 * ## Server Controller. Commands:
 * # Load nginx/php-fpm/mysql
 * serv [(start|stop|reload... - any parameters that nginx/php-fpm/mysql accept)]
 * # Load nginx/php-fpm
 * serv-min [(start|stop|reload... - any parameters that nginx/php-fpm accept)]
 */

require('src/root');
/**
 * ANSI escape code
 * @var string
 */
$CSI = "\x1B[";

/**
 * HELP
 */
callHelp::callHelpExplicit($argv);
($argv[1] !== null)?: callHelp::callHelp($argv);

/**
 * Configuration
 */

echo "\n".$CSI."36;40m" . "--- CLIKE CLI received following parameters:" . $CSI . "0m". "\n";

for ($i=1; $i < count($argv); $i++)
{
	echo '['.$argv[$i].'] ';
}
echo "\n\n";

switch (strstr($argv[1], ':', true)?: $argv[1]) {
	case 'config':
		callHelp::callHelp($argv);
		break;
	case 'server':
		new Server($argv)?: callHelp::callHelp($argv);
		break;
	case 'git':
		new Git($argv)?: callHelp::callHelp($argv);
		break;
	case 'store':
		new Storage($argv)?: callHelp::callHelp($argv);
		break;

	default:
		callHelp::callHelp($argv);
		break;
}
